export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#faf9f6",
        "surface-dim": "#dbdad7",
        "surface-bright": "#faf9f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f1",
        "surface-container": "#efeeeb",
        "surface-container-high": "#e9e8e5",
        "surface-container-highest": "#e3e2e0",
        "on-surface": "#1a1c1a",
        "on-surface-variant": "#464742",
        "inverse-surface": "#2f312f",
        "inverse-on-surface": "#f2f1ee",
        primary: "#111110",
        "on-primary": "#ffffff",
        "primary-container": "#1c1c1a",
        "on-primary-container": "#858382",
        secondary: "#5f5e5a",
        "on-secondary": "#ffffff",
        "secondary-container": "#e2dfd9",
        "on-secondary-container": "#63635e",
        outline: "#777871",
        "outline-variant": "#c7c7c0",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        mode: {
          study: "#2563eb",
          "study-bg": "#eff6ff",
          dsa: "#059669",
          "dsa-bg": "#ecfdf5",
          doubt: "#d97706",
          "doubt-bg": "#fffbeb",
          interview: "#0d9488",
          "interview-bg": "#f0fdfa",
          gaming: "#6366f1",
          "gaming-bg": "#eef2ff",
          party: "#e11d48",
          "party-bg": "#fff1f2",
          chill: "#ca8a04",
          "chill-bg": "#fefce8",
          brainstorm: "#0284c7",
          "brainstorm-bg": "#f0f9ff",
        },
      },
      fontFamily: {
        display: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      boxShadow: {
        subtle: "0 1px 2px rgba(17, 17, 16, 0.04), 0 1px 1px rgba(17, 17, 16, 0.02)",
        elevation: "0 4px 12px -2px rgba(17, 17, 16, 0.06), 0 2px 4px -2px rgba(17, 17, 16, 0.03)",
        modal: "0 20px 25px -5px rgba(17, 17, 16, 0.1), 0 8px 10px -6px rgba(17, 17, 16, 0.06)",
      },
      borderRadius: {
        squircle: "8px",
      },
    },
  },
  plugins: [],
};
